daw2/daw2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('encuestas/',include('encuestas.urls')),
    path('admin/', admin.site.urls),
]

daw2/encuestas/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'encuestas'
urlpatterns = [
	path('', views.index, name='index'),
    path('<int:pregunta_id>/',views.detalle,name="detalle"),
    path('<int:pregunta_id>/resultados/',views.resultados,name="resultados"),
    path('<int:pregunta_id>/votar/',views.votar,name="votar"),
    
    path('accounts/login/',
    auth_views.LoginView.as_view(template_name='encuestas/login.html'),name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('categoria/',views.categoria_create_read,name='categoria'),
    path('updateCategoria/<int:categoria_id>',views.categoria_update,name='updateCategoria'),
    path('deleteCategoria/<int:categoria_id>',views.categoria_delete,name='deleteCategoria'),

    path('updatePregunta/<int:pregunta_id>', views.pregunta_update, name='updatePregunta'),
    path('deletePregunta/<int:pregunta_id>', views.pregunta_delete, name='deletePregunta'),
    path('deleteOpcion/<int:opcion_id>', views.opcion_delete, name='deleteOpcion'),

    path('usuario/',views.usuarios,name='usuarios'),
    path('updateUsuarioAjax/',views.usuario_form_ajax,name='UsuarioFormAjax'),
]

daw2/encuestas/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime 
from django.utils import timezone

# Create your models here.
class Usuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    edad = models.SmallIntegerField(null=True)
    def __str__(self):
        return '{} {} años'.format(self.user,self.edad)

@receiver(post_save, sender=User)
def create_user_usuario(sender, instance, created, **kwargs):
    if created:
        Usuario.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_usuario(sender, instance, **kwargs):
    instance.usuario.save()

class Categoria(models.Model):
    categoria_text = models.CharField(max_length=200)
    class Meta:
        ordering = ['categoria_text']
    def __str__(self):
        return '{}'.format(self.categoria_text)

class Pregunta(models.Model):
    pregunta_text = models.CharField(max_length=200)
    fecha_pub = models.DateTimeField('Fecha de Publicación')
    categoria = models.ManyToManyField(Categoria, related_name='pregunta',blank=True)
    creador = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    class Meta:
        ordering = ['fecha_pub','pregunta_text']
    def __str__(self):
        return '{}      (Fecha de publicación: {})'.format(self.pregunta_text,self.fecha_pub)
    def fue_publicado_recientemente(self):
        return self.fecha_pub >= timezone.now() - datetime.timedelta(days=1)

class Opcion(models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    opcion_text = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    class Meta:
        ordering = ['opcion_text']
    def __str__(self):
        return '{}'.format(self.opcion_text)

daw2/encuestas/forms.py
from django import forms
from .models import Categoria, Pregunta, User, Usuario


class CategoriaForm(forms.ModelForm):


    class Meta:
        model = Categoria

        fields = [
            'categoria_text',
        ]

        labels = {
            'categoria_text': 'Categoría',
        }
        
        widgets = {
            'categoria_text': forms.TextInput(attrs={'class':'form-control'}),
        }

class PreguntaForm(forms.ModelForm):

    class Meta:
        model = Pregunta

        fields = [
            'pregunta_text',
            'categoria',
        ]
        labels = {
            'pregunta_text': 'Pregunta',
            'categoria': 'Categoría',
        }
        widgets = {
            'pregunta_text': forms.TextInput(attrs={'class':'form-control'}),
            # 'categoria': forms.CheckboxSelectMultiple(attrs={'class':''}),
            'categoria': forms.SelectMultiple(attrs={'size':'5','class':'formcontrol','required':'True'}),
        }

class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username','password','first_name', 'last_name', 'email')

        widgets = {
            'username':
                forms.TextInput(attrs={'class':'form-control','autocomplete':'new-text'}),
            'password':
                forms.PasswordInput(attrs={'class':'form-control','autocomplete':'new-password'}),
            'first_name': forms.TextInput(attrs={'class':'form-control'}),
            'last_name': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.EmailInput(attrs={'class':'form-control'}),
        }


class UsuarioForm(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = [
            'edad',
        ]

        widgets = {
            'edad': forms.NumberInput(attrs={'class':'form-control'}),
        }

daw2/encuestas/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from .models import Pregunta, Opcion, Categoria, User, Usuario
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.utils import timezone

from .forms import CategoriaForm, PreguntaForm, UserForm, UsuarioForm

@login_required
def categoria_create_read(request):
    if not request.user.is_superuser: # Control de acceso unicamente para superuser
        raise PermissionDenied

    if request.method == 'POST':
        form = CategoriaForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('encuestas:categoria')
    else:
        form = CategoriaForm()
        categorias = Categoria.objects.all()
        print(categorias)
        contexto = {'form':form,'categorias':categorias}
        return render(request,'encuestas/categorias.html',contexto)


@login_required
def categoria_update(request, categoria_id):
    if not request.user.is_superuser:
        raise PermissionDenied

    categoria = Categoria.objects.get(id=categoria_id)
    if request.method == 'GET':
        form = CategoriaForm(instance=categoria)
    else:
        form = CategoriaForm(request.POST, instance=categoria)
        if form.is_valid():
            form.save()
        return redirect('encuestas:categoria')
    categorias = Categoria.objects.all()
    contexto = {'form':form,'categorias':categorias,'categoria':categoria}
    return render(request,'encuestas/categorias.html',contexto)


@login_required
def categoria_delete(request, categoria_id):
    if not request.user.is_superuser:
        raise PermissionDenied


    categoria = Categoria.objects.get(id=categoria_id)
    if request.method == 'POST':
        categoria.delete()
        return redirect('encuestas:categoria')
    contexto = {'categoria':categoria}
    return render(request,'encuestas/categoria_delete.html',contexto)

@login_required
def index(request):
    if request.method == 'POST':
        form = PreguntaForm(request.POST)
        if form.is_valid():
            preguntaAGuardar = form.save(commit=False)
            preguntaAGuardar.creador = request.user.usuario
            preguntaAGuardar.fecha_pub = timezone.now()
            preguntaAGuardar.save()
            preguntaAGuardar.categoria.set(form.cleaned_data['categoria'])
        return redirect('encuestas:index')
    else:
        form = PreguntaForm()
        # lista_ultimas_preguntas = Pregunta.objects.order_by('-fecha_pub')[:5]
        lista_ultimas_preguntas = Pregunta.objects.all()
        contexto = {'form':form,'lista_ultimas_preguntas':lista_ultimas_preguntas}
        return render(request,'encuestas/index.html',contexto)

@login_required
def pregunta_update(request,pregunta_id):
    pregunta = Pregunta.objects.get(id=pregunta_id)
    if request.method == 'GET':
        form = PreguntaForm(instance=pregunta)
    else:
        form = PreguntaForm(request.POST, instance=pregunta)
        if form.is_valid():
            form.save()
        return redirect('encuestas:index')
    lista_ultimas_preguntas = Pregunta.objects.all()
    contexto = {'form':form,'lista_ultimas_preguntas':lista_ultimas_preguntas,'pregunta':pregunta}
    return render(request,'encuestas/index.html',contexto)

@login_required
def pregunta_delete(request,pregunta_id):
    pregunta = Pregunta.objects.get(id=pregunta_id)
    if request.method == 'POST':
        pregunta.delete()
        return redirect('encuestas:index')
    contexto = {'pregunta':pregunta}
    return render(request,'encuestas/pregunta_delete.html',contexto)

@login_required
def opcion_delete(request,opcion_id):
    opcion = get_object_or_404(Opcion, pk=opcion_id)
    if request.method == 'POST':
        opcion.delete()
        return redirect('encuestas:detalle',opcion.pregunta.id)
    else:
        return render(request,'encuestas/detalle_delete.html',{'opcion':opcion})

@login_required
def detalle(request, pregunta_id):
    pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
    if request.method == 'POST':
        nueva_opcion = Opcion(opcion_text=request.POST['opcion_text'],pregunta=pregunta)
        nueva_opcion.save()
        return redirect('encuestas:detalle',pregunta_id)
    else:
        return render(request,'encuestas/detalle.html',{'pregunta':pregunta})

@login_required
def resultados(request, pregunta_id):
    pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
    return render(request,'encuestas/resultados.html',{'pregunta':pregunta})

@login_required
def votar(request, pregunta_id):
    pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
    try:
        opcion_seleccionada = pregunta.opcion_set.get(pk=request.POST['opcion'])
    except(KeyError, Opcion.DoesNotExist):
        return render(request,'encuestas/detalle.html', {
            'pregunta':pregunta,
            'mensaje_error':"No has seleccionado ninguna opción"
        })
    else:
        opcion_seleccionada.votos += 1
        opcion_seleccionada.save()
        return HttpResponseRedirect(reverse('encuestas:resultados',args=(pregunta_id,)))

@login_required
def usuarios(request):
    if not request.user.is_superuser:
        raise PermissionDenied

    if request.method == 'POST':
        if request.POST['id_user']:
            id_user = request.POST['id_user']
            if 'eliminar' in request.POST:
                userDelete = User.objects.get(id=id_user)
                userDelete.delete()
                return redirect('encuestas:usuarios')

            userUpdate = User.objects.get(id=id_user)
            user_form = UserForm(request.POST, instance=userUpdate)
            usuario_form = UsuarioForm(request.POST,instance=userUpdate.usuario)
            if user_form.is_valid() and usuario_form.is_valid():
                userUpdate = user_form.save()
                userUpdate.set_password(userUpdate.password)
                userUpdate.save()
                usuario_form.save()
        else:
            user_form = UserForm(request.POST)
            if user_form.is_valid():
                userAdd = user_form.save() # lo guardamos y recogemos en variable
                userAdd.set_password(userAdd.password) # cambiamos contraseña
                userAdd.save()
                usuario_form = UsuarioForm(request.POST,instance=userAdd.usuario)
                # obtenemos el usuario del formulario del user guardado anteriormente
                usuario_form.save()
        return redirect('encuestas:usuarios')
    else:
        usuarios = Usuario.objects.all()
        contexto = {'usuarios':usuarios}
        return render(request,'encuestas/usuarios.html',contexto)
@login_required
def usuario_form_ajax(request):
    id_usuario = int(request.GET['id_usuario']) # Lo convierto a entero

    if id_usuario != -1: # Si es una actualizacion
        usuario = Usuario.objects.get(id=id_usuario)
        form_user = UserForm(instance=usuario.user)
        form_usuario = UsuarioForm(instance=usuario)
        contexto = {'usuario':usuario, 'form_user':form_user, 'form_usuario':form_usuario}

    else:
        form_user = UserForm()
        form_usuario = UsuarioForm()
        contexto = {'form_user':form_user, 'form_usuario':form_usuario}

    return render(request,'encuestas/usuarios_formulario.html',contexto)

daw2/encuestas/templates/encuestas/categoria_delete.html
{% extends 'base/base.html' %}

{% block activar3 %}
    <li class="nav-item active">
{% endblock %}

{% block titulo %}
    <h3 class="mt-5">¿Desea eliminar la categoría: {{ categoria }}?</h3>
{% endblock %}

{% block contenido %}
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Si, eliminar</button>
        <a class="btn btn-default" href="{% url 'encuestas:categoria' %}">Cancelar</a>
    </form>
{% endblock %}

daw2/encuestas/templates/encuestas/categorias.html
{% extends 'base/base.html' %}

{% block activar3 %}
    <li class="nav-item active">
{% endblock %}

{% block titulo %}
 Categorías
{% endblock %}

{% block contenido %}
    <table class="table table-sm">
        <thead>
            <tr>
                <th>#</th>
                <th>Categoría</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% if categorias %}
                {% for categoria in categorias %}
                    <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ categoria.categoria_text }}</td>
                    <td>
                    <a class="btn btn-primary btnsm" href="{% url 'encuestas:updateCategoria' categoria.id %}#modificar">Editar</a>
                    <a class="btn btn-danger btnsm" href="{% url 'encuestas:deleteCategoria' categoria.id %}">Borrar</a>
                    </td>
                    </tr>
                {% endfor %}
            {% else %}
                <h2 class="mt-5">No hay Categorías</h2>
            {% endif %}
        </tbody>
    </table>
    <hr id="modificar">
    {% if categoria %}
        <h2 class="mt-5">Modificar Categoría: {{ categoria }}</h2>
    {% else %}
        <h2 class="mt-5">Añadir Categoría</h2>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
{% endblock %}

daw2/encuestas/templates/encuestas/detalle.html
{% extends 'base/base.html' %}

{% block activar1 %}
    <li class="nav-item active">
{% endblock %}

{% block titulo %}
    {{ pregunta.pregunta_text }}
{% endblock %}
{% block contenido %}
    <br>
    {% if mensaje_error %}<p><strong>{{ mensaje_error }}</strong></p>{% endif %}
    <form action="{% url 'encuestas:votar' pregunta.id %}" method="post">
    {% csrf_token %}
    {% for opcion in pregunta.opcion_set.all %}
        {% if user.is_superuser or pregunta.creador.user == user %}
            <a style='text-decoration:none;' href="{% url 'encuestas:deleteOpcion' opcion.id %}">
            <span class="badge badge-danger ml-1">borrar</span>
            </a>
            &nbsp;&nbsp;
        {% endif %}
        <input type="radio" name="opcion" id="opcion{{ forloop.counter }}" value="{{ opcion.id }}">
        <label for="opcion{{ forloop.counter }}">{{ opcion.opcion_text }}</label>
        <br>
    {% endfor %}
    <input type="submit" value="Votar">
    </form>
    {% if user.is_superuser or pregunta.creador.user == user %}
    <br><br>
    <form method="post">
        {% csrf_token %}
        <p>
            <label for="id_opcion_text">Nueva Opción:</label>
            <input type="text" name="opcion_text" class="formcontrol" maxlength="200" required id="id_opcion_text">
        </p>
        <input type="submit" value="Añadir Opción" class="btn btn-success">
    </form>
    {% endif %}
{% endblock %}

daw2/encuestas/templates/encuestas/detalle_delete.html
{% extends 'base/base.html' %}

{% block activar1 %}
    <li class="nav-item active">
{% endblock %}

{% block titulo %}
    <h3 class="mt-5">¿Desea eliminar la Opcion: {{ opcion.opcion_text }}?</h3>
{% endblock %}

{% block contenido %}
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Si, eliminar</button>
        <a class="btn btndefault" href="{% url 'encuestas:detalle' opcion.pregunta.id %}">Cancelar</a>
    </form>
{% endblock %}

daw2/encuestas/templates/encuestas/index.html
{% extends 'base/base.html' %}

{% block activar1 %}
    <li class="nav-item active">
{% endblock %}

{% block titulo %}
    Encuestas disponibles
{% endblock %}

{% block contenido %}
    <table class="table table-sm">
        <thead>
            <tr>
                <th>#</th>
                <th>Pregunta</th>
                <th>Nº Opciones</th>
                <th>Categorías</th>
                <th>Fecha Publicación</th>
                <th>Creador</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% if lista_ultimas_preguntas %}
            {% for pregunta in lista_ultimas_preguntas %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="{% url 'encuestas:detalle' pregunta.id %}">{{ pregunta.pregunta_text }}</a>
                </td>
                <td class="text-center">{{ pregunta.opcion_set.count }}</td>
                <td>
                    {% for categoria in pregunta.categoria.all %}
                        {{ categoria }}
                    {% endfor %}
                </td>
                <td>{{ pregunta.fecha_pub }}</td>
                <td>{{ pregunta.creador.user }}</td>
                <td>
                    {% if user.is_superuser or pregunta.creador.user == user %}
                        <a class="btn btn-primary btnsm" href="{% url 'encuestas:updatePregunta' pregunta.id %}#modificar">Editar</a>
                        <a class="btn btn-danger btnsm" href="{% url 'encuestas:deletePregunta' pregunta.id %}">Borrar</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
            {% else %}
                <h2 class="mt-5">No hay Preguntas</h2>
            {% endif %}
        </tbody>
    </table>
    <hr id="modificar">
    {% if pregunta %}
        <h2 class="mt-5">Modificar Pregunta: {{ pregunta.pregunta_text }}</h2>
    {% else %}
        <h2 class="mt-5">Añadir Pregunta</h2>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
{% endblock %}

daw2/encuestas/templates/encuestas/login.html
{% extends 'base/base.html' %}

{% block titulo %}
    Encuestas Daw 2
{% endblock %}

{% block contenido %}
    {% if user.is_authenticated %}
        <br><br><br><br>
        <p class="lead">
            Bienvenido {{ user }}
        </p>
    {% else %}
        {% if form.errors %}
            <p class="text-danger text-center">
                <strong> La contraseña o el nombre de usuario no son validos</strong>
            </p>
        {% endif %}

        <form class="text-center" action="{% url 'encuestas:login' %}" method="post">
            {% csrf_token %}
            <h1 class="h3 mb-3 font-weight-normal">Log in</h1><br>
            <input type="text" name="username" id="username" class="form-control col-lg-4 mx-auto" placeholder="Usuario" required autofocus>
            <br>
            <input type="password" name="password" id="password" class="form-control col-lg-4 mx-auto" placeholder="Password" required>
            <br>
            <input type="hidden" name="next" value="{{ next }}">
            <button class="btn btn-lg btn-primary" type="submit">Entrar</button>
        </form>
    {% endif %}
{% endblock %}

daw2/encuestas/templates/encuestas/pregunta_delete.html
{% extends 'base/base.html' %}

{% block activar1 %}
    <li class="nav-item active">
{% endblock %}

{% block titulo %}
    <h3 class="mt-5">¿Desea eliminar la pregunta: {{ pregunta.pregunta_text }}?</h3>
{% endblock %}

{% block contenido %}
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Si, eliminar</button>
        <a class="btn btn-default" href="{% url 'encuestas:index' %}">Cancelar</a>
    </form>
{% endblock %}

daw2/encuestas/templates/encuestas/resultados.html
{% extends 'base/base.html' %}


{% block activar1 %}
    <li class="nav-item active">
{% endblock %}

{% block titulo %}
    {{ pregunta.pregunta_text }}
{% endblock %}

{% block contenido %}
    <br>
    <ul>
    {% for opcion in pregunta.opcion_set.all %}
        <li>{{ opcion.opcion_text }} -- {{ opcion.votos }} voto{{ opcion.votos|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'encuestas:detalle' pregunta.id %}">Votar de nuevo</a>
{% endblock %}

daw2/encuestas/templates/encuestas/usuarios.html
{% extends 'base/base.html' %}

{% block activar2 %}
    <li class="nav-item active">
{% endblock %}

{% block titulo %}
 Usuarios
{% endblock %}

{% block contenido %}
    <table class="table table-sm">
        <thead>
            <tr>
                <th>#</th>
                <th>Usuario</th>
                <th>Nombre</th>
                <th>Apellidos</th>
                <th>Email</th>
                <th>Edad</th>
            </tr>
        </thead>
        <tbody>
            {% if usuarios %}
            {% for usuario in usuarios %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ usuario.user }}</td>
                <td>{{ usuario.user.first_name }}</td>
                <td>{{ usuario.user.last_name }}</td>
                <td>{{ usuario.user.email }}</td>
                <td>{{ usuario.edad }}</td>
                <td>
                    <a data-toggle="modal" data-target="#form_usuario"
                        class="btn btn-primary btn-sm"
                        onclick="actualizaUser('{{ usuario.id }}')" href="#">
                    Editar
                    </a>
                    {% if not usuario.user.is_superuser %}
                        <form method="post" action="{% url 'encuestas:usuarios' %}"
                 onsubmit="return confirm('¿Deseas eleminar el usuario: {{ usuario.user }}?');"
                style="display: inline">
                            {% csrf_token %}
                            <input type="hidden" name="id_user" value="{{ usuario.user.id }}">
                            <input type="hidden" name="eliminar" value="1">
                            <button type="submit" class="btn btn-danger btn-sm">Borrar</button>
                        </form>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
            {% else %}
                <h2 class="mt-5">No hay Usuarios</h2>
            {% endif %}
        </tbody>
    </table>
    <button type="button" class="btn btn-secondary" data-toggle="modal"
        data-target="#form_usuario" onclick="actualizaUser(-1)">Añadir Usuario</button>

    <!-- Modal -->
    <div id="form_usuario" class="modal fade" tabindex="-1" role="dialog"
        aria-labelledby="form_usuarioTitle" aria-hidden="true">
        <div id="form_usuario_ajax" class="modal-dialog modal-dialog-centered modal-lg"
        role="document">
        </div>
    </div>

{% endblock %}
{% block js %}
    <script>
        function actualizaUser(id_usuario){
            $.ajax({
                data: {'id_usuario':id_usuario},
                url: "{% url 'encuestas:UsuarioFormAjax' %}",
                type: 'get',
                success: function(data) {
                    $("#form_usuario_ajax").html(data);
                },
                error: function(data) {
                    alert("no datos");
                },
            });
        }
    </script>
{% endblock %}

daw2/encuestas/templates/encuestas/usuarios_formulario.html
<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title" id="form_usuarioTitle">
            {% if usuario %}
            Modificar Usuario: {{ usuario.user }}
            {% else %}
            Añadir Usuario
            {% endif %}
        </h5>
    </div>
    <form method="post" autocomplete="off">
        <div id="conten_form_usuario" class="modal-body">
        {% csrf_token %}
        <table>
            {{ form_user.as_table }}
            {{ form_usuario.as_table }}
        </table>
    
        <input type="hidden" name="id_user" value="{{ usuario.user.id }}">
    
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </form>
</div>