daw2/daw2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('encuestas/',include('encuestas.urls')),
    path('admin/', admin.site.urls),
]

daw2/encuestas/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'encuestas'
urlpatterns = [
	path('', views.index, name='index'),
    path('<int:pregunta_id>/',views.detalle,name="detalle"),
    path('<int:pregunta_id>/resultados/',views.resultados,name="resultados"),
    path('<int:pregunta_id>/votar/',views.votar,name="votar"),
    
    path('accounts/login/',
    auth_views.LoginView.as_view(template_name='encuestas/login.html'),name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('categoria/',views.categoria_create_read,name='categoria'),
    path('updateCategoria/<int:categoria_id>',views.categoria_update,name='updateCategoria'),
    path('deleteCategoria/<int:categoria_id>',views.categoria_delete,name='deleteCategoria'),

    path('updatePregunta/<int:pregunta_id>', views.pregunta_update, name='updatePregunta'),
    path('deletePregunta/<int:pregunta_id>', views.pregunta_delete, name='deletePregunta'),
    path('deleteOpcion/<int:opcion_id>', views.opcion_delete, name='deleteOpcion'),

    path('usuario/',views.usuarios,name='usuarios'),
    path('updateUsuarioAjax/',views.usuario_form_ajax,name='UsuarioFormAjax'),
]

daw2/encuestas/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime 
from django.utils import timezone

# Create your models here.
class Usuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    edad = models.SmallIntegerField(null=True)
    def __str__(self):
        return '{} {} años'.format(self.user,self.edad)

@receiver(post_save, sender=User)
def create_user_usuario(sender, instance, created, **kwargs):
    if created:
        Usuario.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_usuario(sender, instance, **kwargs):
    instance.usuario.save()

class Categoria(models.Model):
    categoria_text = models.CharField(max_length=200)
    class Meta:
        ordering = ['categoria_text']
    def __str__(self):
        return '{}'.format(self.categoria_text)

class Pregunta(models.Model):
    pregunta_text = models.CharField(max_length=200)
    fecha_pub = models.DateTimeField('Fecha de Publicación')
    categoria = models.ManyToManyField(Categoria, related_name='pregunta',blank=True)
    creador = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    class Meta:
        ordering = ['fecha_pub','pregunta_text']
    def __str__(self):
        return '{}      (Fecha de publicación: {})'.format(self.pregunta_text,self.fecha_pub)
    def fue_publicado_recientemente(self):
        return self.fecha_pub >= timezone.now() - datetime.timedelta(days=1)

class Opcion(models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    opcion_text = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    class Meta:
        ordering = ['opcion_text']
    def __str__(self):
        return '{}'.format(self.opcion_text)

daw2/encuestas/forms.py
from django import forms
from .models import Categoria, Pregunta, User, Usuario


class CategoriaForm(forms.ModelForm):


    class Meta:
        model = Categoria

        fields = [
            'categoria_text',
        ]

        labels = {
            'categoria_text': 'Categoría',
        }
        
        widgets = {
            'categoria_text': forms.TextInput(attrs={'class':'form-control'}),
        }

class PreguntaForm(forms.ModelForm):

    class Meta:
        model = Pregunta

        fields = [
            'pregunta_text',
            'categoria',
        ]
        labels = {
            'pregunta_text': 'Pregunta',
            'categoria': 'Categoría',
        }
        widgets = {
            'pregunta_text': forms.TextInput(attrs={'class':'form-control'}),
            # 'categoria': forms.CheckboxSelectMultiple(attrs={'class':''}),
            'categoria': forms.SelectMultiple(attrs={'size':'5','class':'formcontrol','required':'True'}),
        }

class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username','password','first_name', 'last_name', 'email')

        widgets = {
            'username':
                forms.TextInput(attrs={'class':'form-control','autocomplete':'new-text'}),
            'password':
                forms.PasswordInput(attrs={'class':'form-control','autocomplete':'new-password'}),
            'first_name': forms.TextInput(attrs={'class':'form-control'}),
            'last_name': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.EmailInput(attrs={'class':'form-control'}),
        }


class UsuarioForm(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = [
            'edad',
        ]

        widgets = {
            'edad': forms.NumberInput(attrs={'class':'form-control'}),
        }

daw2/encuestas/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from .models import Pregunta, Opcion, Categoria, User, Usuario
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.utils import timezone

from .forms import CategoriaForm, PreguntaForm, UserForm, UsuarioForm

@login_required
def categoria_create_read(request):
    if not request.user.is_superuser: # Control de acceso unicamente para superuser
        raise PermissionDenied

    if request.method == 'POST':
        form = CategoriaForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('encuestas:categoria')
    else:
        form = CategoriaForm()
        categorias = Categoria.objects.all()
        print(categorias)
        contexto = {'form':form,'categorias':categorias}
        return render(request,'encuestas/categorias.html',contexto)


@login_required
def categoria_update(request, categoria_id):
    if not request.user.is_superuser:
        raise PermissionDenied

    categoria = Categoria.objects.get(id=categoria_id)
    if request.method == 'GET':
        form = CategoriaForm(instance=categoria)
    else:
        form = CategoriaForm(request.POST, instance=categoria)
        if form.is_valid():
            form.save()
        return redirect('encuestas:categoria')
    categorias = Categoria.objects.all()
    contexto = {'form':form,'categorias':categorias,'categoria':categoria}
    return render(request,'encuestas/categorias.html',contexto)


@login_required
def categoria_delete(request, categoria_id):
    if not request.user.is_superuser:
        raise PermissionDenied


    categoria = Categoria.objects.get(id=categoria_id)
    if request.method == 'POST':
        categoria.delete()
        return redirect('encuestas:categoria')
    contexto = {'categoria':categoria}
    return render(request,'encuestas/categoria_delete.html',contexto)

@login_required
def index(request):
    if request.method == 'POST':
        form = PreguntaForm(request.POST)
        if form.is_valid():
            preguntaAGuardar = form.save(commit=False)
            preguntaAGuardar.creador = request.user.usuario
            preguntaAGuardar.fecha_pub = timezone.now()
            preguntaAGuardar.save()
            preguntaAGuardar.categoria.set(form.cleaned_data['categoria'])
        return redirect('encuestas:index')
    else:
        form = PreguntaForm()
        # lista_ultimas_preguntas = Pregunta.objects.order_by('-fecha_pub')[:5]
        lista_ultimas_preguntas = Pregunta.objects.all()
        contexto = {'form':form,'lista_ultimas_preguntas':lista_ultimas_preguntas}
        return render(request,'encuestas/index.html',contexto)

@login_required
def pregunta_update(request,pregunta_id):
    pregunta = Pregunta.objects.get(id=pregunta_id)
    if request.method == 'GET':
        form = PreguntaForm(instance=pregunta)
    else:
        form = PreguntaForm(request.POST, instance=pregunta)
        if form.is_valid():
            form.save()
        return redirect('encuestas:index')
    lista_ultimas_preguntas = Pregunta.objects.all()
    contexto = {'form':form,'lista_ultimas_preguntas':lista_ultimas_preguntas,'pregunta':pregunta}
    return render(request,'encuestas/index.html',contexto)

@login_required
def pregunta_delete(request,pregunta_id):
    pregunta = Pregunta.objects.get(id=pregunta_id)
    if request.method == 'POST':
        pregunta.delete()
        return redirect('encuestas:index')
    contexto = {'pregunta':pregunta}
    return render(request,'encuestas/pregunta_delete.html',contexto)

@login_required
def opcion_delete(request,opcion_id):
    opcion = get_object_or_404(Opcion, pk=opcion_id)
    if request.method == 'POST':
        opcion.delete()
        return redirect('encuestas:detalle',opcion.pregunta.id)
    else:
        return render(request,'encuestas/detalle_delete.html',{'opcion':opcion})

@login_required
def detalle(request, pregunta_id):
    pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
    if request.method == 'POST':
        nueva_opcion = Opcion(opcion_text=request.POST['opcion_text'],pregunta=pregunta)
        nueva_opcion.save()
        return redirect('encuestas:detalle',pregunta_id)
    else:
        return render(request,'encuestas/detalle.html',{'pregunta':pregunta})

@login_required
def resultados(request, pregunta_id):
    pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
    return render(request,'encuestas/resultados.html',{'pregunta':pregunta})

@login_required
def votar(request, pregunta_id):
    pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
    try:
        opcion_seleccionada = pregunta.opcion_set.get(pk=request.POST['opcion'])
    except(KeyError, Opcion.DoesNotExist):
        return render(request,'encuestas/detalle.html', {
            'pregunta':pregunta,
            'mensaje_error':"No has seleccionado ninguna opción"
        })
    else:
        opcion_seleccionada.votos += 1
        opcion_seleccionada.save()
        return HttpResponseRedirect(reverse('encuestas:resultados',args=(pregunta_id,)))

@login_required
def usuarios(request):
    if not request.user.is_superuser:
        raise PermissionDenied

    if request.method == 'POST':
        if request.POST['id_user']:
            id_user = request.POST['id_user']
            if 'eliminar' in request.POST:
                userDelete = User.objects.get(id=id_user)
                userDelete.delete()
                return redirect('encuestas:usuarios')

            userUpdate = User.objects.get(id=id_user)
            user_form = UserForm(request.POST, instance=userUpdate)
            usuario_form = UsuarioForm(request.POST,instance=userUpdate.usuario)
            if user_form.is_valid() and usuario_form.is_valid():
                userUpdate = user_form.save()
                userUpdate.set_password(userUpdate.password)
                userUpdate.save()
                usuario_form.save()
        else:
            user_form = UserForm(request.POST)
            if user_form.is_valid():
                userAdd = user_form.save() # lo guardamos y recogemos en variable
                userAdd.set_password(userAdd.password) # cambiamos contraseña
                userAdd.save()
                usuario_form = UsuarioForm(request.POST,instance=userAdd.usuario)
                # obtenemos el usuario del formulario del user guardado anteriormente
                usuario_form.save()
        return redirect('encuestas:usuarios')
    else:
        usuarios = Usuario.objects.all()
        contexto = {'usuarios':usuarios}
        return render(request,'encuestas/usuarios.html',contexto)
@login_required
def usuario_form_ajax(request):
    id_usuario = int(request.GET['id_usuario']) # Lo convierto a entero

    if id_usuario != -1: # Si es una actualizacion
        usuario = Usuario.objects.get(id=id_usuario)
        form_user = UserForm(instance=usuario.user)
        form_usuario = UsuarioForm(instance=usuario)
        contexto = {'usuario':usuario, 'form_user':form_user, 'form_usuario':form_usuario}

    else:
        form_user = UserForm()
        form_usuario = UsuarioForm()
        contexto = {'form_user':form_user, 'form_usuario':form_usuario}

    return render(request,'encuestas/usuarios_formulario.html',contexto)

daw2/encuestas/templates/base/base.html
{% load static %}
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Encuestas</title>
    <script src="http://code.jquery.com/jquery-3.4.1.min.js"></script>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/sticky-footer-navbar/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'encuestas/css/bootstrap.css' %}" rel="stylesheet">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'encuestas/css/sticky-footer-navbar.css' %}" rel="stylesheet">
  </head>
  <body class="d-flex flex-column h-100">
    {% block header %}
    <header>
    <!-- Fixed navbar -->
    {% if user.is_authenticated %}
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="{% url 'encuestas:login' %}">Encuestas</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarCollapse" aria-controls="navbarCollapse"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    {% block activar1 %}
                        <li class="nav-item">
                    {% endblock %}
                    <a class="nav-link" href="{% url 'encuestas:index' %}">Preguntas</a>
                    </li>
                    {% if user.is_superuser %}
                        {% block activar2 %}
                        <li class="nav-item">
                        {% endblock %}
                            <a class="nav-link" href="{% url 'encuestas:usuarios' %}">Usuarios</a>
                        </li>
                        {% block activar3 %}
                            <li class="nav-item">
                        {% endblock %}
                            <a class="nav-link" href="{% url 'encuestas:categoria' %}">Categorías</a>
                        </li>
                    {% endif %}
                </ul>
                <h4 class="form-inline mt-2 mt-md-0 text-white">
                    <strong> {{ user }} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>
                </h4>
                <form class="form-inline mt-2 mt-md-0" action="{% url 'encuestas:logout' %}"
                method="get">
                <button class="btn btn-outline-success my-2 my-sm-0"
                type="submit">Salir</button>
                </form>
            </div>
        </nav>
    {% endif %}
    </header>
 {% endblock %}

<!-- Begin page content -->
<main role="main" class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">
      {%block titulo %}
      Título del apartado
      {% endblock %}
    </h1>
    {%block contenido %}
    <p class="lead"> Contenido...</p>
    {% endblock %}
  </div>
</main>

{% block footer %}
<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">Tutorial Djago --- CPIFP Bajo Aragón</span>
  </div>
</footer>
{% endblock %}
<script src="http://code.jquery.com/jquery-3.4.1.min.js"></script>
      <script src="{% static 'encuestas/js/boostrap.bundle.min.js' %}" ></script></body>
    {% block js %}     
    {% endblock %}
</body>
</html>